"""
    Cielo24

    The cielo24 Web Services Platform API allows developers to easily integrate transcription, captioning and keyword extraction into their applications without having to use a manual web portal.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: devs@cielo24.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from cielo24.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from cielo24.exceptions import ApiAttributeError


def lazy_import():
    from cielo24.model.iwp_enum import IWPEnum
    globals()['IWPEnum'] = IWPEnum


class JobOptions(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('customer_approval_steps',): {
            'TRANSLATION': "TRANSLATION",
            'RETURN': "RETURN",
        },
        ('customer_approval_tool',): {
            'AMARA': "AMARA",
            'CIELO24': "CIELO24",
        },
        ('speaker_id',): {
            'TRUE': "true",
            'FALSE': "false",
        },
        ('audio_description',): {
            'TRUE': "true",
            'FALSE': "false",
        },
        ('on_screen_text',): {
            'TRUE': "true",
            'FALSE': "false",
        },
        ('music_lyrics',): {
            'TRUE': "true",
            'FALSE': "false",
        },
        ('custom_special_handling',): {
            'TRUE': "true",
            'FALSE': "false",
        },
    }

    validations = {
        ('notes',): {
            'max_length': 1000,
        },
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'customer_approval_steps': ([str],),  # noqa: E501
            'customer_approval_tool': (str,),  # noqa: E501
            'custom_metadata': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},),  # noqa: E501
            'notes': (str,),  # noqa: E501
            'return_iwp': ([IWPEnum],),  # noqa: E501
            'generate_media_intelligence_iwp': ([IWPEnum],),  # noqa: E501
            'speaker_id': (str,),  # noqa: E501
            'audio_description': (str,),  # noqa: E501
            'on_screen_text': (str,),  # noqa: E501
            'music_lyrics': (str,),  # noqa: E501
            'custom_special_handling': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'customer_approval_steps': 'customer_approval_steps',  # noqa: E501
        'customer_approval_tool': 'customer_approval_tool',  # noqa: E501
        'custom_metadata': 'custom_metadata',  # noqa: E501
        'notes': 'notes',  # noqa: E501
        'return_iwp': 'return_iwp',  # noqa: E501
        'generate_media_intelligence_iwp': 'generate_media_intelligence_iwp',  # noqa: E501
        'speaker_id': 'speaker_id',  # noqa: E501
        'audio_description': 'audio_description',  # noqa: E501
        'on_screen_text': 'on_screen_text',  # noqa: E501
        'music_lyrics': 'music_lyrics',  # noqa: E501
        'custom_special_handling': 'custom_special_handling',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """JobOptions - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            customer_approval_steps ([str]): Requires your approval of a job at specified points in the workflow. When the job is ready for approval you will be emailed a link that will take you to a web based tool you can use to view, edit and approve the job. You may request approval at two points in the workflow: before translation and before the job is returned.. [optional] if omitted the server will use the default value of []  # noqa: E501
            customer_approval_tool (str): Determines which web based tool to use for viewing, editing and approving jobs.. [optional] if omitted the server will use the default value of "CIELO24"  # noqa: E501
            custom_metadata ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): A JSON dictionary of key value pairs. These will be used as substitution strings when building the callback URL and custom DFXP caption header.. [optional]  # noqa: E501
            notes (str): Allows you to provide text that will be displayed to the transcriber when the job is processed. An HTML included will be escaped.. [optional] if omitted the server will use the default value of ""  # noqa: E501
            return_iwp ([IWPEnum]): Allows you to receive additional callbacks when interim versions of the job are completed. If you specified a callback_url, then a callback will sent for FINAL regardless of the value of this option.. [optional] if omitted the server will use the default value of []  # noqa: E501
            generate_media_intelligence_iwp ([IWPEnum]): Requests that media intelligence be generated for the specified interim/final versions of the transcript. Media intelligence data is added to the ElementList and can be retrieve using the get_elementlist API call. See [ElementList](https://cielo24.readthedocs.io/en/latest/output_formats/elementlist.html#media-intelligence-label) for details.. [optional] if omitted the server will use the default value of []  # noqa: E501
            speaker_id (str): Requests that speaker names be identified.. [optional] if omitted the server will use the default value of "false"  # noqa: E501
            audio_description (str): Requests that all noises and sounds be identified.. [optional] if omitted the server will use the default value of "false"  # noqa: E501
            on_screen_text (str): Requests that any text that appears in the media be added to the transcription.. [optional] if omitted the server will use the default value of "false"  # noqa: E501
            music_lyrics (str): Requests that lyrics to songs be transcribed instead of labeled [MUSIC].. [optional] if omitted the server will use the default value of "false"  # noqa: E501
            custom_special_handling (str): Requests that transcribers follow submitted instruction set.. [optional] if omitted the server will use the default value of "false"  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', True)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """JobOptions - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            customer_approval_steps ([str]): Requires your approval of a job at specified points in the workflow. When the job is ready for approval you will be emailed a link that will take you to a web based tool you can use to view, edit and approve the job. You may request approval at two points in the workflow: before translation and before the job is returned.. [optional] if omitted the server will use the default value of []  # noqa: E501
            customer_approval_tool (str): Determines which web based tool to use for viewing, editing and approving jobs.. [optional] if omitted the server will use the default value of "CIELO24"  # noqa: E501
            custom_metadata ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): A JSON dictionary of key value pairs. These will be used as substitution strings when building the callback URL and custom DFXP caption header.. [optional]  # noqa: E501
            notes (str): Allows you to provide text that will be displayed to the transcriber when the job is processed. An HTML included will be escaped.. [optional] if omitted the server will use the default value of ""  # noqa: E501
            return_iwp ([IWPEnum]): Allows you to receive additional callbacks when interim versions of the job are completed. If you specified a callback_url, then a callback will sent for FINAL regardless of the value of this option.. [optional] if omitted the server will use the default value of []  # noqa: E501
            generate_media_intelligence_iwp ([IWPEnum]): Requests that media intelligence be generated for the specified interim/final versions of the transcript. Media intelligence data is added to the ElementList and can be retrieve using the get_elementlist API call. See [ElementList](https://cielo24.readthedocs.io/en/latest/output_formats/elementlist.html#media-intelligence-label) for details.. [optional] if omitted the server will use the default value of []  # noqa: E501
            speaker_id (str): Requests that speaker names be identified.. [optional] if omitted the server will use the default value of "false"  # noqa: E501
            audio_description (str): Requests that all noises and sounds be identified.. [optional] if omitted the server will use the default value of "false"  # noqa: E501
            on_screen_text (str): Requests that any text that appears in the media be added to the transcription.. [optional] if omitted the server will use the default value of "false"  # noqa: E501
            music_lyrics (str): Requests that lyrics to songs be transcribed instead of labeled [MUSIC].. [optional] if omitted the server will use the default value of "false"  # noqa: E501
            custom_special_handling (str): Requests that transcribers follow submitted instruction set.. [optional] if omitted the server will use the default value of "false"  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
