# flake8: noqa

"""
    Cielo24

    The cielo24 Web Services Platform API allows developers to easily integrate transcription, captioning and keyword extraction into their applications without having to use a manual web portal.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: devs@cielo24.com
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from cielo24.api_client import ApiClient

# import Configuration
from cielo24.configuration import Configuration

# import exceptions
from cielo24.exceptions import OpenApiException
from cielo24.exceptions import ApiAttributeError
from cielo24.exceptions import ApiTypeError
from cielo24.exceptions import ApiValueError
from cielo24.exceptions import ApiKeyError
from cielo24.exceptions import ApiException
